### PR TITLE
Bring recent metno/python3 updates inline with requirements at smhi

### PR DESCRIPTION
**Pull request by adybbroe**
This PR does a few things:
 - Cleaning up after recent merged PRs from Met Norway
 - Add trollsift to required packages and fix utils
 - Update versioning - use setuptools_scm to handle versioning
 - Add pygrib as a requirement
 - Add hook to let PPS send posttroll messages

### CODE REVIEW

**Comment by TAlonglong** [comment]
At least you need to change here https://github.com/pytroll/pytroll-pps-runner/blob/master/nwcsafpps_runner/metno_update_nwp.py#L31

change helper_functions to utils and remove `run_shell_command`

**Comment by adybbroe** [comment]
@TAlonglong I am merging this now. I hope you will be able to handle it!?

**Comment by pnuu** [comment]
The PR just came "ready for review" 8 minutes ago. Please give some time for the review.

**Comment by adybbroe** [comment]
Yes, right @pnuu ! I will try hard waiting till after Easter in case @TAlonglong is not online these days

**Pull request merged**
