### PR TITLE
Use orbit number from message.

### LINKED ISSUE #41: level1c runner read orbit_number from posttroll message
To allow for the orbit number to follow the processing allow the level 1c runner to read and use the orbit number from the posttroll message.

Add it as a configurable options.

### PR DESCRIPTION
**Pull request by TAlonglong**
Use orbit number from message if configured.

Else hardcoded value in the initialiser is used which may cause problems in downstream processing eg. pps-runner.

 - [X] Closes #41  
 - [X] Tests added 
 - [X] Tests passed: Passes ``pytest nwcsafpps_runner`` 
 - [X] Passes ``flake8 nwcsafpps_runner`` 
 - [ ] Fully documented

### CODE REVIEW

**Review by pnuu — COMMENTED** [review]
Does `Use orbit number from message if configured` in the description mean `if message contains the orbit number`? Otherwise LGTM.

**Comment by TAlonglong** [comment]
No, it means you have to add a configure option. 

But I have just figured out this does not work as the level1c4pps software does not respect any input. So it will require a major addition to level1c4pps to work which I will not do.

I accept that the orbit number is hardcoded to 00000

**Comment by pnuu** [comment]
Oh, ok. Then I would've asked to add the required config option to the examples, but if it isn't respected in any case :man_shrugging:

**Review by adybbroe — APPROVED** [review]
Thanks for this! Looks fine to me

**Pull request merged**
