### PR TITLE
Changes needed for python3 

### PR DESCRIPTION
**Pull request by TAlonglong**
Chages needed for python3

Not sure about the ´__hash__´ for SceneId but I added it…to make it work. Not tested with python2

### CODE REVIEW

**Comment by TAlonglong** [comment]
As long as you dont provide `nhsf_file_name_sift` in the config file, but just the variable you use then it will work as before.

As I said I have not tested with python2.

**Comment by adybbroe** [comment]
@TAlonglong I am merging this now, and we hope the nwp-stuff is okay for us as well, otherwise we need to look at it again

**Comment by adybbroe** [comment]
@TAlonglong Could you perhaps provide an example on how you pass the `nhsf_file_name_sift`?

**Comment by TAlonglong** [comment]
OK, is it ok if add a new example file?

Or should I add a new section in the exiting one?

**Comment by adybbroe** [comment]
@TAlonglong A new section in the existing one would be my proposal, but I trust you to decide best

**Pull request merged**
